version: '3'

networks:
    avr-nginx-php-mysql:

services:
    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: avr-nginx-container
        ports:
            - "9011:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-service
            - mysql-service
        networks:
            - avr-nginx-php-mysql

    # php
    php-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: avr-php-container
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/app
        networks:
            - avr-nginx-php-mysql
    # mysql
    mysql-service:
        image: mysql:8
        container_name: avr-mysql-container
        ports:
            - "4406:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - avr-nginx-php-mysql